version: '3.8'

services:

  pgsql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vbnb
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgsql-test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vbnb-test
    ports:
      - "5433:5432"
    networks:
      - app_network

  springapi:
    depends_on:
      - pgsql
    build: ./backend/vbnb
    container_name: spring-boot-api-container
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    name: app_network
