version: '3.8'

services:

  pgsql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vbnb
    ports:
      - "5432:5432"

  pgsql-test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vbnb-test
    ports:
      - "5433:5432"
